import Provider from "./components/Context";
import "./globals.css";
import Backgound from "./components/Backgound";
import Nav from "./components/Nav";
import Lines from "./components/Lines";
import Footer from "./components/Footer";

export const metadata = {
  title: "Ship Design Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth snap-mandatory snap-y snap-center">
      <Provider>
        <body className={`no-scrollbar`}>
          <Lines />
          <Backgound />
          <Nav />
          <main>{children}</main>
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
