import { Inter } from "next/font/google";
import "./globals.css";
import Backgound from "./components/Backgound";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ship Design Engineering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " " + "no-scrollbar"}>
        <Nav />
        <main className="relative overflow-hidden pt-[20vh] ">
          <Backgound />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
