import Provider from "../components/Context";
import "./globals.css";
import Backgound from "../components/Backgound";
import Nav from "../components/Nav";
import Lines from "../components/Lines";
import Footer from "../components/Footer";
import initTranslations from "../i18n";
import TranslationsProvider from "../components/TranslationsProivider";

export const metadata = {
  title: "Ship Design Engineering",
  description: "Generated by create next app",
};

const i18nNamespaces = ["home", "about", "services", "projects", "common"];

export default async function RootLayout({ children, params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="en" className="scroll-smooth no-scrollbar">
      <Provider>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          <body className="relative min-h-screen flex flex-col ">
            <Backgound />
            <Nav />
            {children}
            <Footer />
          </body>
        </TranslationsProvider>
      </Provider>
    </html>
  );
}
